canonical/canonicalwebteam.discourse

canonicalwebteam/discourse_docs/app.py
canonicalwebteam/discourse_docs/exceptions.py
canonicalwebteam/discourse_docs/parsers.py
setup.py
tests/fixtures/forum_mock.py
tests/test_app.py

Parse a section entitled "URLs" in the index page to create a mapping from pretty URLs to topic IDs and vice-versa.
Then we:
- Redirect to the pretty URL
- Replace links to the topic ID with the pretty URL in navigation
This topic is an example of how the URL map looks:
https://forum.snapcraft.io/t/future-index-page/11127
QA
--
This can be QAed using the [`pretty-urls` branch of docs.snapcraft.io](https://github.com/nottrobin/docs.snapcraft.io/tree/pretty-urls) (whose `requirements.txt` points to this branch), as follows:
``` bash
git clone -b pretty-urls https://github.com/nottrobin/docs.snapcraft.io.git docs.snapcraft.io-pretty-urls
cd docs.snapcraft.io-pretty-urls
./run
```
Now go to http://0.0.0.0:8030, and check:
- That all the URLs in the left navigation are "pretty" (as in …

Pretty urls

---

canonicalwebteam/discourse_docs/app.py
canonicalwebteam/discourse_docs/parsers.py
setup.py
tests/fixtures/forum_mock.py
tests/test_app.py

Just like with the "URLs" section, this adds support for a "Redirects" section, which will contain a mapping table of "path"s to "location"s for defining redirect mappings.
The format for this section is described here:
https://github.com/nottrobin/canonicalwebteam.discourse-docs/blob/b86df3ccfb779c4f4033d5714d94312b667114b0/canonicalwebteam/discourse_docs/parsers.py#L96-L126
If an invalid redirect is encountered, ["Warning" HTTP headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Warning) will be sent. This will also happen if one of the redirect paths clashes with one of the pretty URLs in the URLs map.
QA
--
The simplest way to review this at this stage is to read the tests, check they make sense, and then check they pass: …

Support "Redirects" in the Index page content

---

CHANGES.txt
canonicalwebteam/discourse_docs/app.py
setup.py
tests/test_app.py

When a user tries to access a topic that does not belong to the docs category, he is now redirected to the topic on the forum.
- Checkout master on `docs.snapcraft.io`.
- In the requirements file do:
```
-canonicalwebteam.discourse-docs==0.3.0
+git+https://github.com/jpmartinspt/canonicalwebteam.discourse-docs.git@redirect_instead_404#egg=canonicalwebteam.discourse-docs
```
- Go to http://0.0.0.0:8030/11365 and make sure you are redirected to `forum.snapcraft.io/t/multipass-does-not-start-on-ubuntu-server-18-04/11365`
- Go to http://0.0.0.0:8030/multipass-does-not-start-on-ubuntu-server-18-04/11365 and make sure you are redirected to `forum.snapcraft.io/t/multipass-does-not-start-on-ubuntu-server-18-04/11365`
- Go to http://0.0.0.0:8030/multipass-does-not-start-on-ubuntu-server-18-04 and …

Redirect instead of 404 for non 'doc' topics

---

CHANGES.txt
canonicalwebteam/discourse_docs/app.py
canonicalwebteam/discourse_docs/parsers.py
setup.py

The URL prefix work had a couple of problems, e.g.:
- https://maas-io-canonical-web-and-design-pr-346.run.demo.haus/docs/t/explore-maas/787 ends up at https://maas-io-canonical-web-and-design-pr-346.run.demo.haus/docs/docs/explore-maas (extra `/docs`)
- It would sometimes get into a redirect loop
- Pretty URLs weren't being replaced in left nav
This branch should hopefully fix those issues in a more thorough way.
QA
--
This can be QAed by using this demo (built from the [upgrade-docs-module](https://github.com/nottrobin/maas.io/tree/upgrade-docs-module) branch, which installs `discourse-docs` from this branch):
https://maas-io-canonical-web-and-design-pr-348.run.demo.haus/
Check:

Fix URL prefixes

---

CHANGES.txt
canonicalwebteam/discourse_docs/__init__.py
canonicalwebteam/discourse_docs/app.py
canonicalwebteam/discourse_docs/parsers.py
setup.py
tests/test_app.py

Pass DocParser to DiscourseDocs, so that it can be used outside by client projects.

parser.parse

---

CHANGES.txt
canonicalwebteam/discourse_docs/app.py
setup.py
tests/test_app.py

Add a `/sitemap.txt` endpoint which will lists all the URLs in the URL map.
This will help with getting our docs URLs indexed by Google (for a longer explanation see https://github.com/canonical-web-and-design/maas.io/pull/370)
QA
--
`./setup test` - See the `test_sitemap` test pass.

v0.6.1: /sitemap.txt

---

CHANGES.txt
canonicalwebteam/discourse_docs/parsers.py
setup.py

- Add in context the the var sections that gives a split of the `body_html` by h2
- bump to v0.7.0
```
-e git+https://github.com/tbille/canonicalwebteam.docs.git@add-sections#egg=canonicalwebteam.discourse-docs
```
- in the file `webapp/app.py`
```py
url_prefix = "/tutorials"
tutorials_docs_parser = DocParser(
api=DiscourseAPI(base_url="https://discourse.ubuntu.com/"),
index_topic_id=13611,
url_prefix=url_prefix,
)
tutorials_docs = DiscourseDocs(
parser=tutorials_docs_parser,
category_id=34,
document_template="/docs/document.html",
url_prefix=url_prefix,
blueprint_name="tutorials",
)
tutorials_docs.init_app(app)
```
-  on the file: `/templates/docs/document.html`
```
-        {{ document.body_html | safe }}
+ …
```

Add sections to context

---

.python-version
canonicalwebteam/discourse_docs/parsers.py

- Add in context the the var sections that gives a split of the `body_html` by h2
- bump to v0.7.0
```
-e git+https://github.com/tbille/canonicalwebteam.docs.git@add-remaining-duration#egg=canonicalwebteam.discourse-docs
```
- in the file `webapp/app.py`
```py
url_prefix = "/tutorials"
tutorials_docs_parser = DocParser(
api=DiscourseAPI(base_url="https://discourse.ubuntu.com/"),
index_topic_id=13611,
url_prefix=url_prefix,
)
tutorials_docs = DiscourseDocs(
parser=tutorials_docs_parser,
category_id=34,
document_template="/docs/document.html",
url_prefix=url_prefix,
blueprint_name="tutorials",
)
tutorials_docs.init_app(app)
```
-  on the file: `/templates/docs/document.html`
```
-        {{ document.body_html | safe }} …
```

Add remaning duration

---

canonicalwebteam/discourse_docs/app.py
canonicalwebteam/discourse_docs/parsers.py

- Add in context the metadata read from the discourse index: https://discourse.ubuntu.com/t/about-the-tutorials-category/13611
The idea here is that you can have a undefined number of column and the parser will create a list of dictionaries with the keys based on the column name. 
```
-e git+https://github.com/tbille/canonicalwebteam.docs.git@add-metadata-parsing#egg=canonicalwebteam.discourse-docs
```
- in the file `webapp/app.py`
```py
url_prefix = "/tutorials"
tutorials_docs_parser = DocParser(
api=DiscourseAPI(base_url="https://discourse.ubuntu.com/"),
index_topic_id=13611,
url_prefix=url_prefix,
)
tutorials_docs = DiscourseDocs(
parser=tutorials_docs_parser,
category_id=34, …
```

Add metadata parsing

---

.github/workflows/publish.yml

We agreed to should use an specific commit ID for the GitHub Action "gh-action-pypi-publish" to avoid issues like this one: https://github.com/pypa/gh-action-pypi-publish/issues/20

Set commit id for GH Action

---

CHANGES.txt
canonicalwebteam/discourse_docs/parsers.py
setup.py

Mistake was done. The duration in tutorails is MM:SS not HH:MM
```
-e git+https://github.com/tbille/canonicalwebteam.docs.git@fix-timeparsing#egg=canonicalwebteam.discourse-docs
```

Fix parsing duration

---

CHANGES.txt
canonicalwebteam/discourse_docs/app.py
canonicalwebteam/discourse_docs/models.py
canonicalwebteam/discourse_docs/parsers.py
setup.py
tests/fixtures/forum_mock.py
tests/test_app.py

- It seems that dicsourse when having to many internal links struggles to get the title of a topic. (eg. https://discourse.ubuntu.com/t/about-the-tutorials-category/13611 )
- To fix this, I call the category api and loop through it to get all the topics of a category (since not possible to make a unique api call I have to loop until I reach the end. https://docs.discourse.org/#tag/Categories/paths/~1c~1{id}.json/get )
- Then I go through the soup  and replace the text in every `a` tag
This is a breaking change since the category id is no part of the parser
```
-e git+https://github.com/tbille/canonicalwebteam.docs.git@parse-categories#egg=canonicalwebteam.discourse-docs
```
- in the file `webapp/app.py`
```py …
```

Parse categories api to get correct urls

---

CHANGES.txt
canonicalwebteam/discourse_docs/parsers.py
setup.py

Fixes https://github.com/canonical-web-and-design/snapcraft.io/issues/2517 and https://github.com/canonical-web-and-design/snapcraft.io/issues/2516
The last version of this module has created an AttributeError issue in some of Snapcraft.io doc pages, eg:
https://snapcraft.io/docs/supported-snap-hooks
https://snapcraft.io/docs/writing-local-plugins
This change fixes the issue.
Follow the QA in this PR:
https://github.com/canonical-web-and-design/snapcraft.io/pull/2520

Fix AttributeError in some docs

---

CHANGES.txt
canonicalwebteam/discourse_docs/parsers.py
setup.py

microk8s.io/docs/addon-ambassador returns NoneType because there is no space to strip, it starts with a emoticon. So added a condition for that.
QA in microk8s, make sure <https://microk8s.io/docs/addon-ambassador> is accessible
Fixes #41 
Fixes https://github.com/canonical-web-and-design/microk8s.io/issues/300

Fix micro8s.io/docs/addon-ambassador 500 error

---

CHANGES.txt
canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/parsers/base_parser.py
canonicalwebteam/discourse/parsers/docs_parser.py
canonicalwebteam/discourse/parsers/engage_parser.py
canonicalwebteam/discourse/parsers/parsers.py
setup.py
tests/test_app.py

- Refactor parsers by creating a Base class to extend from as per discussion.
- Return takeovers
- Fix default discourse behavior of turning URLs into anchors
- Checkout this PR https://github.com/canonical-web-and-design/ubuntu.com/pull/8414 
- `docker-compose up -d` if you haven't done it before
- `dotrun --env DISCOURSE_API_KEY=API-key --env DISCOURSE_API_USERNAME="carkod" ` Get the API-Key in Last Pass
Make sure there is nothing broken by visiting:
- `/tutorials`
- `/server/docs`
- `/engage`
- FInally check that json data for takeovers is showing up on `/`
Fixes #49

Refactor parsers

---

CHANGES.txt
canonicalwebteam/discourse/parsers/docs_parser.py

Improve current lightbox solution, by removing meta div.
This addresses the Anbox-cloud issue where images are too small (see issue below). This solution emulates a "lightbox", by allowing the user to click on the image, since we cannot recreate lightbox effect as it needs JS.
- Install this version on anbox-cloud project by adding `git+git://github.com/carkod/canonicalwebteam.discourse.git@replace-lightbox#egg=canonicalwebteam.discourse` to requirements.txt
- `dotrun clean`
- `dotrun`
- Go to `/docs/manage/streaming-android-applications` and check that the image can be opened in a larger view.
- As a comparison, you can check the current ubuntu.com/docs/manage/streaming-android-applications to see the difference
- Install this version on ubuntu.com project by adding …

Remove meta div that breaks Vanilla

---

CHANGES.txt
canonicalwebteam/discourse/parsers/base_parser.py
setup.py
tests/fixtures/forum_mock.py
tests/test_app.py

Make the url_prefix optional in the url_map
The URL map can look like this now, if `url_prefix==/docs`:
```
[details=Mapping table]
| Topic | Slug |
| -- | -- |
| <discourse_url> | /toto |
| <discourse_url> | tata |
| <discourse_url> | /docs/titi |
[/details]
```
This means that: 
```
[details=Mapping table]
| Topic | Slug |
| -- | -- |
| <discourse_url> | /toto |   -> /docs/toto
| <discourse_url> | tata |   -> /docs/tata
| <discourse_url> | /docs/titi |    -> /docs/titi
[/details]
```
- add this module to charmhub
- Run charmhub with module and go on:
- http://0.0.0.0:8045/mattermost/docs
- Compare with URL map here: https://discourse.charmhub.io/t/mattermost-documentation-overview/3758

Make url_prefix optionnal in url map

---

CHANGES.txt
canonicalwebteam/discourse/app.py
setup.py
tests/cassettes/TestDiscourseAPI.test_active_page_returns_200.yaml
tests/cassettes/TestDiscourseAPI.test_active_page_returns_adds_no_meta_with_preview_flag.yaml
tests/cassettes/TestDiscourseAPI.test_inactive_page_returns_302.yaml
tests/cassettes/TestDiscourseAPI.test_inactive_page_returns_page_with_preview_flag.yaml
tests/fixtures/templates/engage.html
tests/test_engage_pages.py

Redirect inactive engage page to discourse unless there is a `preview` flag.
For the sake of the QA I made /engage/it/deployment-azienda-manuale active = false. It will not affect prod in any way because the feature is not live yet.
1. Go to https://ubuntu-com-8761.demos.haus/engage/it/deployment-azienda-manuale you will be redirected to its discourse page.
2. Go to https://ubuntu-com-8761.demos.haus/engage/it/deployment-azienda-manuale?preview you will see the page
Press `ctrl + u` in browser. Use search to look for the meta tag robot. You will see it has the value `nofollow`.
3.  Go to https://ubuntu-com-8761.demos.haus/engage/it/redhat-openstack-confronto-manuale (an active page). Press `ctrl + u` in browser. Use search to look for the meta tag `robot`. It won't be there.
Fixes: …

Add preview feature

---

README.md

See that the example now imports DocsParser which is required by the example.

Fix the get started example to include all modules

---

README.md
canonicalwebteam/discourse/__init__.py
canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/parsers/__init__.py
canonicalwebteam/discourse/parsers/base_parser.py
canonicalwebteam/discourse/parsers/tutorials_parser.py
setup.py
tests/test_app.py

- Rename DocParser to TutorialParser, fixes https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/59

Rename DocParser to TutorialParser

---

canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/parsers/docs.py
setup.py
tests/test_app.py

- Update warning header name from `warning` to `discourse-warning`.
- Removed '199 canonicalwebteam.discourse ' at the beginning of each header value
- Remove false possitive warnings and improve warnings messages for:
- Missing topic link for a path
- Missing path for a topic link
Follow the QA instruction here https://github.com/canonical-web-and-design/dqlite.io/pull/100

Fix warnings headers

---

canonicalwebteam/discourse/parsers/docs.py

- Nav table: Ignore levels higher than 3 (https://github.com/canonical-web-and-design/snap-squad/issues/1786)
**I didn't increase the version number because I want this change to be part of the next release.**
It's already QAed by me
1. Clone dqlite locally
2. Change the discourse topic
3. Create a navigation table with more than 3 levels

Nav table: Ignore levels higher than 3

---

canonicalwebteam/discourse/parsers/base_parser.py
setup.py
tests/test_app.py

When there are relative links on Discourse topics that are not part of the URL mapping, the parser keeps the same relative path creating a bad URL, like:
`/t/setting-up-static-kubernetes-storage-tutorial/1193` => `juju.is/t/setting-up-static-kubernetes-storage-tutorial/1193`
With this change, these relative paths will be transformed into absolute paths linking to the Discourse topic if the path is not part of the URL mapping.
QA on juju.is: https://github.com/canonical-web-and-design/juju.is/pull/174

Fix for relative links on Discourse

---

canonicalwebteam/discourse/parsers/base_parser.py
setup.py
tests/test_parser.py

Make user references in discourse posts link to their discourse profile.
Ex: Parsing `<a href="/u/joao.martins">@joao.martins</a>` in discourse.ubuntu.com post should result in `<a href="https://discourse.ubuntu.com/u/joao.martins">@joao.martins</a>`
Use https://github.com/canonical-web-and-design/webteam.canonical.com/pull/53 to QA.
Enables fixing of #99 we need to bump `microk8s.io` to `canonicalwebteam.discourse==4.0.1`

User references in posts should link to the user's discourse profile

---

canonicalwebteam/discourse/parsers/docs.py
setup.py

If we had multiple navigation links pointing at different fragments of the same
topic the fragments would be overwritten by the fragment of the last processed
link when building the URL map.

Allow different fragments on navigation links pointing to the same topic

---

canonicalwebteam/discourse/parsers/docs.py
setup.py

- Allow doc writers to use empty levels in the navigation table. Empty levels will allow URL mapping without displaying them in the navigation
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/2144

Hidden nav items

---

canonicalwebteam/discourse/parsers/docs.py
setup.py

- Fix unexpected render of a random discourse topics
- Add `git+git://github.com/carkod/canonicalwebteam.discourse@unexpected-render#egg=canonicalwebteam.discourse` to your requirements.txt on ubuntu.com repo.
- `dotrun clean && dotrun` the project and check that e.g. http://localhost:8001/server/docs/t/nvidia-driver-specific-flutter-bug/25269 is returning a 404.
- Compare with current https://ubuntu.com/server/docs/t/nvidia-driver-specific-flutter-bug/25269 is returning a page, this shouldn't happen.
Additionally, to be 100% sure we are not breaking other docs (if any of the other docs have some obscure feature), we can try the same thing on anbox-cloud.io/docs/t/nvidia-driver-specific-flutter-bug/25269, maas.io/docs/t/nvidia-driver-specific-flutter-bug/25269, …

Fix unexpected render of any discourse topic

---

canonicalwebteam/discourse/parsers/base_parser.py
canonicalwebteam/discourse/parsers/engage.py
setup.py

- Check missing links for engage pages
Use this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/9368)
Fixes #75

Check missing links for engage pages

---

README.md
examples/document.html

Adds an example template for documentation websites using the module and updates the README to link it.
Once it's merged into the repo the [documentation on Discourse](https://discourse.canonical.com/t/creating-discourse-based-documentation-pages/159) will be also updated accordingly.

Add an example of documentation template

---

examples/document.html

By default the example should use the fully expanded side navigation.

Use non-expandable navigation by default

---

examples/document.html

Makes sure the nested navigation items are always expanded if their parent does not have a page linked (in the expandable side navigation).
This is based on enhancement introduced in [multipass.run docs template](https://github.com/canonical-web-and-design/multipass.run/blob/21155dbd029ac3569c1e1c3388a5f7cb0671355b/templates/docs/document.html#L6-L34)

Expand items that are not linked in navigation

---

canonicalwebteam/discourse/parsers/docs.py
setup.py

An [issue was reported on Snapcraft](https://github.com/canonical-web-and-design/snapcraft.io/issues/4068).
I tracked the issue down to the table on https://forum.snapcraft.io/t/snap-tutorials/30848 having the heading “Tutorials” (as a quick fix I renamed it to “Walkthroughs”).
<assumption>
Based on the docstring I believe tutorial indexes should only have one column.
</assumption>
As such, I've added a check to see if the table has multiple columns (headers).
I am not familiar with this module, so I would greatly appreciate someone in-the-know to double-check my assumption is accurate AND the fix works :).

Improve tutorials topic parsing

---

canonicalwebteam/discourse/app.py
setup.py

When data-explorer doesn't return metadata, return None, so that we can process it in the project (usually a 404)
Check that https://ubuntu-com-11940.demos.haus/engage/not-found goes to 404 instead of 500 (demo comes from [this PR](https://github.com/canonical/ubuntu.com/pull/11940))

Handle 404 for engage pages that don't exist

---

examples/document.html

Updates the example template to latest version of expandable side navigation in introduced in Vanilla 3.7, as in https://github.com/canonical/juju.is/pull/431
- check if the template is the same as in juju.is

Update example with latest version of expandable side navigation for docs

---

README.md
canonicalwebteam/discourse/app.py
setup.py

Currently on cn.u.com (and probably on jp.u.com) engage pages, we are receiving loads of [false positive errors](https://sentry.is.canonical.com/canonical/cn-ubuntu-com/), these errors occur because u.com need this metadata, but cn.u.com don't need it (it's always the same language)
Therefore, an argument was added, so that u.com can pass additional optional metadata checks, instead of enforcing it in the module.
- Go to https://cn-ubuntu-com-637.demos.haus/takeovers
- Now check that we aren't getting more errors on [cn.u.com sentry](https://sentry.is.canonical.com/canonical/cn-ubuntu-com/). Or if you find it difficult to see, you can delete the existing engage pages sentry errors and visit https://ubuntu-com-11864.demos.haus/takeovers again.
If you've got time to compare, to see clearly …

More flexibility to engage pages metadata checks

---

canonicalwebteam/discourse/parsers/base_parser.py
canonicalwebteam/discourse/parsers/docs.py
setup.py
tests/test_parser.py

Signed-off-by: David Edler <david.edler@canonical.com>
Fixes #145

Replace emdash with -- in topic paths to be url compatible #145

---

canonicalwebteam/discourse/models.py
setup.py

Fixes #139 
When a result with no rows and an error message is returned, raise an exception and add a hint, that the API key might be missing.

Improve error reporting

---

canonicalwebteam/discourse/parsers/base_parser.py
canonicalwebteam/discourse/parsers/docs.py
setup.py

- Adds the `_generate_toc` method that get the headings from a discourse document and creates a toc object detailing the headings and there associated potion in the pages hierarchy.
- You can include this PR in place of canonicalwebteam.discourse in your requirements.txt and then run the project as normal.
- For testing purposes I have create a [test-topic](https://discourse.ubuntu.com/t/test-topic/33987) on discourse which can be reached through u.com with the extension `/core/docs/test-topic`
- Currently it does not support toggalable TOC or a headings range

Generate toc based on heading anchor tags

---

canonicalwebteam/discourse/parsers/docs.py

Minor change to fix a bug where the entire headings_map object would become the child of itself

Fix bug when all headings on same level

---

canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/parsers/docs.py
canonicalwebteam/discourse/parsers/tutorials.py
setup.py
tests/test_app.py
tests/test_parser.py

This PR adds `ensure_parsed` to `Docs` and `Tutorials` parsers so that callers can be sure that the metadata is parsed, but not unnecessarily force a re-fetch and parse of that Discourse post.
This aims to increase performance

Don't parse more than we need to

---

canonicalwebteam/discourse/parsers/base_parser.py
canonicalwebteam/discourse/parsers/docs.py
setup.py
tests/test_parser.py

This PR includes several commits that aim to remove slow paths when rendering docs.
Notably it seeks to minimise the number of times we parse HTML, (don't take a `BeautifulSoup`, carve it up, turn it back into a str, then make another `BeautifulSoup`).
It adds tests for the affected functions for extracting sections and allows one to easily drop in different `EXAMPLE_CONTENT` to run the tests with (where one might see times go from > 100s of milliseconds to ~11)
This addresses many of the problems that were [worked](https://github.com/canonical/maas.io/pulls?q=is%3Apr+speedups) [around](https://github.com/canonical/maas.io/pull/687) in maas.io docs which is now [one of the fastest sites we have](https://canonical.github.io/upptime/)

Parsing speedups

---

canonicalwebteam/discourse/parsers/docs.py
setup.py
tests/test_parser.py

Fixes #160 by operating on a copy of the version specific navigation set when decorating with `is_active` and `has_active_child`.
Drive-by fixes for just storing `active_topic_id` and not the whole topic, and fix to an f-string that was missing an f

Don't mutate shared navigation model between requests

---

.github/workflows/tests.yml
.gitignore
README.md
canonicalwebteam/discourse/parsers/base_parser.py
canonicalwebteam/discourse/parsers/docs.py
setup.py
tox.ini

Add's a `tox.ini` file with `lint` and `test` targets, and updates GH workflows to use tox instead.
This also invokes the tests using pytest, which is much nicer to use than `python setup.py test`

Add tox + pytest support

---

canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/parsers/docs.py
canonicalwebteam/discourse/parsers/tutorials.py
setup.py
tests/test_app.py
tests/test_parser.py

This undoes the work done in [PR 156][1], commits [2fc9e17][2], [b7d859][3] and [965aa6][4].
That work was attempting to avoid parsing through the index topic content more often than necessary,
by simply skipping the fetching of that content entirely once it's been downloaded once.
This caused [big problems][5] because no changes to any of the documentation index content, including
navigation updates, would be reflected until the application is re-released.
There may be more sensible ways to avoid parsing the index topic content too many times,
but for now this work needs to be rolled back.
Fixes https://github.com/canonical/canonicalwebteam.discourse/issues/163
Go to https://juju-is-472.demos.haus/docs. Then change something in [the index …

Fix indefinite caching of index content by undoing "ensure_parsed" work

---

canonicalwebteam/discourse/parsers/base_parser.py

Improved the null checking on the next link
- Go to https://ubuntu.com/landscape/docs/quickstart-deployment and see it errors
- Locally change `requirements.txt` of ubuntu.com project to: 
```
canonicalwebteam.discourse @ git+https://github.com/anthonydillon/canonicalwebteam.discourse@check-header-has-link`
```
- Run `dotrun clean && dotrun`
- Go to http://0.0.0.0:8001/landscape/docs/quickstart-deployment
- See that the page loads
- Check a few pages all load correctly

Check it a header contains a link

---

canonicalwebteam/discourse/parsers/base_parser.py
setup.py

Strip white spaces from heading title. In newer versions of discourse the headings titles in cooked html are prefixed with new lines and it breaks the section parsing.
In a few different projects that use discourse(ubuntu.com, maas.io, charmhub.io):
```
canonicalwebteam.discourse @ git+https://github.com/canonical/canonicalwebteam.discourse@heading-title-strip
```
- Run `dotrun clean && dotrun`
- Go to http://0.0.0.0:8001/landscape/docs/quickstart-deployment
- See that the page loads
- Check a few pages all load correctly

Strip heading titles

---

canonicalwebteam/discourse/parsers/tutorials.py
setup.py

Strip white spaces from heading title. In newer versions of discourse the headings titles in cooked html are prefixed with new lines and it breaks the section parsing.
Bumped version
In your local ubuntu.com project do the following in the requirements.txt
```
canonicalwebteam.discourse @ git+https://github.com/anthonydillon/canonicalwebteam.discourse@strip-headings-tutorials
```
- Run `dotrun clean && dotrun`
- Go to http://localhost:8001/tutorials/install-ubuntu-desktop#1-overview
- See that the page loads
- Check a few pages all load correctly

Strip heading titles for tutorials

---

canonicalwebteam/discourse/parsers/base_parser.py
setup.py
tests/test_parser.py

Handle images within a discourse topic - https://discourse.charmhub.io/t/observe-your-charm-with-cos-lite/7814 for example.
QA:
- Pull this branch
- Clone juju.is
- Update juju.is requirements.txt:
```
#canonicalwebteam.discourse==5.4.4
-e ./canonicalwebteam.discourse
```
- Within juju.is run `dotrun -m "/path/to/canonicalwebteam.discourse":"canonicalwebteam.discourse"` (you need the most up to date version of dotrun)
- Visit http://localhost:8041/docs/sdk/observe-your-charm-with-cos-lite and ensure the image at the bottom of the page loads and links to https://discourse.charmhub.io/uploads/default/optimized/2X/4/45cb7e9d3eb7c99cae62e615e3ff59663856e966_2_690x466.png

Handle images in links

---

README.md
examples/README.md
examples/_footer.html
examples/_header.html
examples/document-brochure.html

With new documentation layout being introduced in Vanilla 4.5.0 and tested already on mikrok8s website this provides an example and documentation on how to use it for Flask and Discourse based documentation sites.
Fixes [WD-6056](https://warthogs.atlassian.net/browse/WD-6056)
- review provided docs and templates, make sure you understand how to use it
[WD-6056]: https://warthogs.atlassian.net/browse/WD-6056?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

Update examples and docs for new layout

---

canonicalwebteam/discourse/parsers/base_parser.py

- Adds a function `_remove_trailing_numbers_from_headings` to the base soup parser that ensure trailing numbers are removed from heading anchors
- Run a project that leverages discourse docs locally ie. ubuntu.com
- Specify this branch as the requirement for `canonicalwebteam.discourse`, it will look something like:
```
canonicalwebteam.discourse @ git+https://github.com/canonical/canonicalwebteam.discourse@remove-trailing-numbers
```
- Run `dotrun clean` to remove any old packages and then `dotrun` to reinstall
- If that doesn't work you can download the canonicalwebteam.discourse and check out this branch and then add 
```
-e ../canonicalwebteam.discourse
```
where the requirement for `canonicalwebteam.discourse` would be (I'm assuming they live in the same folder here)
- Once it is …

feat: Add function to ensure trailing numbers are removed from heading anchors

---

canonicalwebteam/discourse/parsers/base_parser.py

Only merge once Vanilla 3.14.0  drops
- Adds def to add anchor links to headings similar to what they have on https://developer.mozilla.org/en-US/docs/Web/CSS/visibility#try_it (for example)
NEW DEMO https://github.com/canonical/ubuntu.com/pull/13989
- Go to https://ubuntu-com-13989.demos.haus/ceph/docs
- hover a link and see it underlines and a anchor tag appear next to it, see https://staging.vanillaframework.io/docs/patterns/links#anchor-link
- click the link and make sure it is appended to the url
https://warthogs.atlassian.net/browse/WD-8606

Adds anchor links to headings

---

canonicalwebteam/discourse/parsers/base_parser.py
setup.py

- This fixed a bug we had in the `_add_anchor_links` func, where headings that had nested content ex. `<h3><code>something</code></h3>` would be duplicated. You can see it here: https://juju.is/docs/juju/hook-tool?efgh
- I changed how we handle the headings so nested content is retained
- Go to https://ubuntu-com-14036.demos.haus/ceph/docs/setting-up-multi-site and see that the heading 'Prerequisites' is not duplicated and is clickable/hover-able as an anchor link
- Check other headings still retain the functionality

bug: Fix bug where if a code block is nested in the heading it gets duplicated

---

README.md
canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/exceptions.py
canonicalwebteam/discourse/models.py
setup.py
tests/cassettes/TestDiscourseAPI.test_index_ep_takeovers.yaml
tests/cassettes/TestDiscourseAPI.test_individual_ep_takeovers.yaml
tests/cassettes/TestDiscourseAPI.test_pagination.yaml
tests/test_engage_pages.py

Add support for pagination for engage pages and takeovers
- Go to https://ubuntu-com-14035.demos.haus/engage
- Add pagination with the URL https://ubuntu-com-14035.demos.haus/engage?limit=5&offset=0
- Go to next page https://ubuntu-com-14035.demos.haus/engage?limit=5&offset=1 and check that items of the following page display correctly
Fixes https://warthogs.atlassian.net/browse/WD-7149
Fixes https://warthogs.atlassian.net/browse/WD-7150

Add limit and offset to allow pagination for engage pages and takeovers

---

README.md
canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/models.py
setup.py
tests/cassettes/TestDiscourseAPI.test_index_ep_takeovers.yaml
tests/cassettes/TestDiscourseAPI.test_pagination.yaml
tests/test_engage_pages.py

- Added sort functionality, order by active -> true and 
- Refactored data explorer query into single one `query_engage_pages_by_param`
- Added count active query that works with pagination.
- Added total count of pages
- Added total count of all items
Most of this work done in [data explorer](https://discourse.ubuntu.com/admin/plugins/explorer?id=16)
1. Go to https://ubuntu-com-14035.demos.haus/engage
2. Scroll down and click next page and/or the numbers to check that next page doesn't repeat the same engage pages.
3. Select language, and check that the correct language of engage pages shows
4. Same for resource types and tags
Do the steps 1 and 2 for https://ubuntu-com-14035.demos.haus/takeovers
Check for https://ubuntu-com-14035.demos.haus/takeovers.json works as usual. 
Test security …

Add sort by functionality to takeovers 'cooked' content

---

setup.py

Apply changes from https://github.com/canonical/canonicalwebteam.discourse/pull/197 and bump version to 5.7.3

chore: Bump version to 5.7.3

---

examples/document.html

Include h3 headings to docs table of contents. Nest h3 items within their corresponding h2 parent headings.
This is a duplicated fix that was addressed here: https://github.com/canonical/juju.is/pull/564
Updating the Discourse repo for consistency!
Fixes https://github.com/canonical/canonicalwebteam.discourse/issues/187

Include h3 to table of contents

---

canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/models.py
setup.py

Updated `query_engage_page_by_param` to include second keyword and value.
This is to allow Engage pages to be queried for multiple type and languages

feat: Update query to include second keyword and value

---

canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/models.py
setup.py

Updated `query_engage_page_by_param` to include filtering by two keywords/value and tags.
This allows engage pages to be filtered by up to three categories. Previously on [prod](https://ubuntu.com/engage) we only limit users to filter by one category each. 
- Go to https://ubuntu-com-14740.demos.haus/engage
- Select multiple filters from dropdown.
- Click on Apply filters button.
- See that page loads according to selected filters.

feat: Add third filter for querying engage pages

---

CHANGELOG.md
canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/models.py
canonicalwebteam/discourse/parsers/category.py
setup.py

- Remove template handling from the Category class. Templates should now be handled by the project that is using the module. This gives greater flexibility to the usage of the class.
- Add a new discourse query `get_last_activity_time` to know whether to update the content without a rebuild. Uses the data explore plugin here https://discourse.ubuntu.com/admin/plugins/explorer?id=122
- Check out [the demo](https://ubuntu-com-14726.demos.haus/security/vulnerabilities) and see the vulnerability pages are still being rendered.

feat(Category): Remove template handling from the Category class

---

CHANGELOG.md
canonicalwebteam/discourse/models.py
setup.py

- Updated the data explorer query
- Updated conditions for params
- u.com/engage page now doesn't show the case-studies that are statically available on canonical.com
- Go to https://ubuntu-com-14848.demos.haus/engage
- Verify the case studies are visible
- Make sure they don't include the static case-studies (case-studies that are hosted statically at canonical.com)

feat: Updated explorer query to filter out static case-studies on ubuntu.com/engage

---

CHANGELOG.md
canonicalwebteam/discourse/parsers/base_parser.py
setup.py

**Added** _inject_custom_css def
A function that finds css directives in the soup and applies to them to the next found element.
Example: `[style=p-table--wide-table]` will apply 'p-table--wide-table' as a class the the element directly after where the directive was found.
- Go to this [Discourse post](https://discourse.ubuntu.com/t/test-topic/59821) and find the table with the string '[style=p-table--wide-table]' above it
- Find the corresponding table in [the demo](https://ubuntu-com-15050.demos.haus/security/vulnerabilities/test-topic). See the string, '[style=p-table--wide-table]', has been removed
- Inspect the table element and see it is wrapped in a div with the class 'p-table--wide-table'
Fixes https://warthogs.atlassian.net/browse/WD-20353

feat: Add function that allows injecting custom css

---

CHANGELOG.md
canonicalwebteam/discourse/__init__.py
canonicalwebteam/discourse/app.py
canonicalwebteam/discourse/models.py
canonicalwebteam/discourse/parsers/__init__.py
canonicalwebteam/discourse/parsers/events.py
setup.py
tests/test_parser.py

refactor: Move update checks to model.py
feat: Create Event and EventParser classes to fetch and parse events from Discourse Calendar plugin
chore: Update readme and changelog
- Open the [demo](https://ubuntu-com-15193.demos.haus/community)
- You should see one result with an id '58898' and the associated event data
- Visit the [post](https://discourse.ubuntu.com/t/ubuntu-at-guadec-2025/58898) of the one result. Check it is an event, it hasn't passed, and it has the tag 'events'

Create Event and EventParser classes

---

CHANGELOG.md
canonicalwebteam/discourse/app.py
setup.py

Remove duplicate tags by normalizing case and whitespace in the `get_engage_pages_tags` function. This enhancement improves the consistency and accuracy of the tags returned. Tags added to engage pages happen to be inconsistent in terms of casing, for example, 'cloud' and 'Cloud', this causes the tags to be returned as duplicates but different in casing.
- Visit [demo](https://ubuntu-com-15299.demos.haus/engage)
- Verify that there are no duplicate tags in the filter select dropdown
https://warthogs.atlassian.net/browse/WD-22509

Normalize case and whitespace in engage page tags retrieval
