- CHANGES.txt
- README.md
- canonicalwebteam/discourse_docs/app.py
- canonicalwebteam/discourse_docs/parsers.py
- setup.py
- tests/test_app.py
- tests/test_models.py
Fix url prefix bug that wasn't handling every routes in the docuemntations.
- @Caleb-Ellis 	we can check together to make it simplier (?)
> Fix url prefix bug

- CHANGES.txt
- canonicalwebteam/discourse_docs/app.py
- setup.py
- tests/test_app.py
This PR fix an issue with the content type returned by the headers in the sitemap.
QA:
- Make sure that the test passed
> Fix sitemap

- CHANGES.txt
- canonicalwebteam/discourse_docs/app.py
- setup.py
- tests/test_app.py
Google needs the domain to be included in the sitemap
QA
--
Check the test checks for the domain, see the test pass
> Add domain to URLs in /sitemap.txt

- CHANGES.txt
- canonicalwebteam/discourse_docs/app.py
- setup.py
Adding an optional parameter to the DiscourseDocs class to be able to instanciate multiple discourse blueprints
> Add name parameter

- CHANGES.txt
- setup.py
> Bump to version v0.8.0

- README.md
There were some interface changes and addictions which were not reflected in the README. 
Read through the usage and check it looks good.
> Update the README usage section

- CHANGES.txt
- README.md
- canonicalwebteam/discourse_docs/parsers.py
- setup.py
- tests/fixtures/forum_mock.py
- tests/test_app.py
Fixes #34 
Make category_id optional so the url map is the only source of truth.
> Make category optional

- .github/release-drafter.yml
- .github/workflows/release-drafter.yml
- .github/workflows/tests.yml
- Add release-drafter action for Discourse module
> Add release-drafter action for Discourse module

- .github/workflows/tests.yml
- canonicalwebteam/discourse/app.py
- canonicalwebteam/discourse/parsers/base_parser.py
- canonicalwebteam/discourse/parsers/docs.py
- canonicalwebteam/discourse/parsers/engage.py
- canonicalwebteam/discourse/parsers/tutorials.py
- Extend docs parser to parse versiontable (https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/62)
- Added dropdown to the template (https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/64)
1. In any proyect update the `requirements.txt` to contain this branch code:
```
git+git://github.com/jkfran/canonicalwebteam.discourse@parse-version-table#egg=canonicalwebteam.discourse
```
2. Update a Discourse topic to include the new navigation table.
3. See it working
**Pair with me if you want to see it working**
> Parse version table

- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Support for levels 1 from the beginning
> Support for levels 1 from the beginning

- .github/workflows/publish.yml
- .github/workflows/tests.yml
- canonicalwebteam/discourse/app.py
- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Support for redirections between versions (https://github.com/canonical-web-and-design/snap-squad/issues/1787)
- Refactor in the docs parser
Follow the QA steps here: https://github.com/canonical-web-and-design/juju.is/pull/166
> Version redirections

- canonicalwebteam/discourse/parsers/base_parser.py
- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Fix navigations links and warnings
https://github.com/canonical-web-and-design/juju.is/pull/166
> Fix navigation links

- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Make index an integer
Follow the QA steps: https://github.com/canonical-web-and-design/charmhub.io/pull/804
> Make index an integer

- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Fix redirections
- Fix redirections warnings
I can show you
> Fix redirections

- canonicalwebteam/discourse/parsers/docs.py
- setup.py
**This PR is for a feature branch**
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1898
> Parse tutorial tables

- canonicalwebteam/discourse/models.py
- canonicalwebteam/discourse/parsers/docs.py
**This PR is pointing to a feature branch**
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1899
> Get multiple topics

- canonicalwebteam/discourse/parsers/docs.py
The table in the tutorials topics will be:
```
| — | ----------------------- |
| Summary | Learn how to deploy Nextcloud and Collabora Online on Ubuntu server, all backed by HTTPS using Let’s Encrypt |
| Categories | cloud |
| Difficulty | 2 |
| Author | Francisco |
```
> Parse metadata table

- canonicalwebteam/discourse/parsers/docs.py
**This PR is pointing to a feature branch**
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1900
> Convert tutorials to cards

- canonicalwebteam/discourse/app.py
- canonicalwebteam/discourse/parsers/base_parser.py
- canonicalwebteam/discourse/parsers/docs.py
- canonicalwebteam/discourse/parsers/tutorials.py
- tests/test_app.py
**This PR is pointing to a feature branch**
Fixes https://github.com/canonical-web-and-design/snap-squad/issues/1951
> Tutorial links

- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Version 4.0.2 introduced an issue with external links, this change fixes the issue.
QA with this PR: https://github.com/canonical-web-and-design/juju.is/pull/259
https://github.com/canonical-web-and-design/juju.is/issues/258
> Fix external links in the navigation

- .github/workflows/publish.yml
- .github/workflows/release-drafter.yml
- .github/workflows/tests.yml
- Adds inclusive naming check
- Lints for 'master', 'slave', 'whitelist', 'blacklist'
Fixes https://app.zenhub.com/workspaces/-web-squad-5931746dba512f05402b61f6/issues/canonical-web-and-design/web-squad/4468
> Add inclusive naming check

- canonicalwebteam/discourse/parsers/base_parser.py
- canonicalwebteam/discourse/parsers/tutorials.py
- Fix tutorials key errors
- Created a source of truth with a list of allowed maps
Use this [PR](https://github.com/canonical-web-and-design/ubuntu.com/pull/10971)
Fixes https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/111
> Fix tutorials key errors

- setup.py
Correction for repo url
Fix https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/119
> Update repo url

- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Fix https://github.com/canonical-web-and-design/canonicalwebteam.discourse/issues/93
> Fix: Support topics without navigation

- .github/workflows/tests.yml
- canonicalwebteam/discourse/app.py
- canonicalwebteam/discourse/parsers/docs.py
- setup.py
- Done add some defence around assumed "children" index
> Defend against out-of-range index of children

- canonicalwebteam/discourse/parsers/base_parser.py
- setup.py
> fix issue with image parsing

- canonicalwebteam/discourse/parsers/base_parser.py
- setup.py
> update image parsing

- .github/workflows/publish.yml
- Updates the pypi publish action to use a more modern worflow
- Merge the PR and check that the action passes
Fixes https://warthogs.atlassian.net/browse/WD-21958
> fix: Publish action fails
